{
  "openapi": "3.1.0",
  "info": {
    "title": "IsThereAnyDeal API",
    "description": "[Changelog](https://github.com/IsThereAnyDeal/API/blob/master/CHANGELOG.md)\n\nIsThereAnyDeal API provides programmatic access to features found at IsThereAnyDeal.  \n\n## Terms of Service\n\nAPI is provided in good faith. We trust you won't misuse the API to damage IsThereAnyDeal, its users or its reputation.\n\n- You MAY use this API for commercial purposes **IF** the resulting app is available to public. If you want to use this API privately contact us.\n- You SHOULD provi[...]",
    "termsOfService": "https://github.com/IsThereAnyDeal/API/blob/master/TERMS_OF_SERVICE.md",
    "version": "2.5.0",
    "contact": {
      "name": "General API contact",
      "email": "api@isthereanydeal.com"
    }
  },
  "servers": [
    {
      "url": "https://api.isthereanydeal.com"
    }
  ],
  "tags": [
    {
      "name": "Lookup",
      "description": "Endpoints for looking up things on IsThereAnyDeal.\n\nEndpoints in `/lookup/` namespace will follow this URL structure: `/lookup/{lookup-what}/{by-what}/`\n\nEndpoints from other namespaces that are related to lookup in any way may also be\nincluded in this category. \n"
    },
    {
      "name": "Game"
    },
    {
      "name": "Prices"
    },
    {
      "name": "History"
    },
    {
      "name": "Bundles"
    },
    {
      "name": "Deals List"
    },
    {
      "name": "Waitlist Games",
      "x-displayName": "Games"
    },
    {
      "name": "Waitlist Stats",
      "x-displayName": "Stats"
    },
    {
      "name": "Collection Games",
      "x-displayName": "Games",
      "description": "Basic Collection operations when you only need to track games, without additional details.\n"
    },
    {
      "name": "Collection Copies",
      "x-displayName": "Copies",
      "description": "Operations on Collection copies. These allow more detailed tracking of owned games.\n"
    },
    {
      "name": "Collection Groups",
      "x-displayName": "Categories",
      "description": "Collection category endpoints. Category and group may be used interchangably. Default category has ID 0.\n"
    },
    {
      "name": "Collection Stats",
      "x-displayName": "Stats"
    },
    {
      "name": "User"
    },
    {
      "name": "User Notes",
      "x-displayName": "Notes",
      "description": "Endpoints for managing notes, that user can create for individual games."
    },
    {
      "name": "Profiles",
      "description": "You can create a link between your app's users' accounts and ITAD, and use that link to sync\ngames into Waitlist and Collection in the similar fashion as natively supported profiles on IsThereAnyDeal.\n"
    },
    {
      "name": "Sync",
      "description": "Sync endpoints provide easier way to add or remove games from Waitlist and Collection.\n\nSync via API works in the same way as natively supported sync of remote profiles, but instead of ITAD pulling data,\nyou will have to push data. Behavior of sync'd games is the same as for natively supported profiles.\n\nIt is useful when you can create a list of all games for user, and don't want to handle game identification,\ndeduplication, additions and removals via regular API end[...]"
    },
    {
      "name": "Shops"
    },
    {
      "name": "Stats"
    },
    {
      "name": "Unstable",
      "description": "Endpoints that are not yet stable. They may be in development, experimental,\nor we are not sure about their current definition.\n"
    },
    {
      "name": "Internal",
      "description": "Endpoints available for our own services. They are documented here for the sake of completeness.\n"
    }
  ],
  "paths": {
    "/lookup/id/title/v1": {
      "post": {
        "operationId": "lookup-gid-title-v1",
        "tags": [
          "Lookup"
        ],
        "summary": "Lookup ITAD game IDs by title",
        "description": "Lookup IsThereAnyDeal's game IDs by title\nThis is not a full fledged search. Some title preprocessing will happen, but the lookup will only return IDs for titles, that match precisely.\nTypos or variations in title may not give you expected result.",
        "security": [
          {},
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/lookup/id/shop/{shopId}/v1": {
      "post": {
        "operationId": "lookup-gid-shopid-v1",
        "tags": [
          "Lookup"
        ],
        "summary": "Lookup ITAD game IDs by IDs on shop",
        "description": "Lookup IsThereAnyDeal's game IDs by shop's game IDs",
        "security": [
          {},
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/lookup/shop/{shopId}/id/v1": {
      "post": {
        "operationId": "lookup-shopid-gid-v1",
        "tags": [
          "Lookup"
        ],
        "summary": "Lookup game IDs on shop by ITAD game IDs",
        "description": "Lookup shop's game IDs by IsThereAnyDeal game IDs",
        "security": [
          {},
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/search/v1": {
      "get": {
        "operationId": "games-search-v1",
        "tags": [
          "Game",
          "Lookup"
        ],
        "summary": "Search",
        "description": "Search for games by title",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/lookup/v1": {
      "get": {
        "operationId": "games-lookup-v1",
        "tags": [
          "Game",
          "Lookup"
        ],
        "summary": "Lookup Game",
        "description": "Lookup game based on title or Steam appid",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/info/v2": {
      "get": {
        "operationId": "games-info-v2",
        "tags": [
          "Game"
        ],
        "summary": "Game Info",
        "description": "Get basic game information",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/prices/v2": {
      "post": {
        "operationId": "games-prices-v2",
        "tags": [
          "Prices"
        ],
        "summary": "Prices",
        "description": "Get games' prices",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/bundles/v2": {
      "get": {
        "operationId": "games-bundles-v2",
        "tags": [
          "Bundles"
        ],
        "summary": "Bundles including Game",
        "description": "Get all bundles which contain the game",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/overview/v2": {
      "post": {
        "operationId": "games-overview-v2",
        "tags": [
          "Prices"
        ],
        "summary": "Price Overview",
        "description": "Get basic price overview for selected games.\n\nFor each game current best price will be loaded (optionally, only from selected shops),\nhistorical low price (among all covered shops).\n\nFurthermore, result will also contain list of currently active bundles,\nwhich contain at least one of the queried games.\n",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/historylow/v1": {
      "post": {
        "operationId": "games-historylow-v1",
        "tags": [
          "History"
        ],
        "summary": "History Low",
        "description": "Get historically lowest prices",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/storelow/v2": {
      "post": {
        "operationId": "games-storelow-v2",
        "tags": [
          "History"
        ],
        "summary": "Store Low",
        "description": "Get historically lowest prices for individual stores",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/games/history/v2": {
      "get": {
        "operationId": "games-history-v2",
        "tags": [
          "History"
        ],
        "summary": "History log",
        "description": "Get log of historical prices",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/deals/v2": {
      "get": {
        "operationId": "deals-v2",
        "tags": [
          "Deals List"
        ],
        "summary": "Deals List",
        "description": "Get current deals. Follows same rules as deals list displayed on the website, which means that\nyou will not get one game more than once in the list.\n\nFor each game, the best price is displayed, ignoring stores that currently don't have game on sale,\neven if they currently have a better price.\n",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/waitlist/games/v1": {
      "get": {
        "operationId": "waitlist-games-v1-get",
        "tags": [
          "Waitlist Games"
        ],
        "summary": "Games in Waitlist",
        "description": "Get games in user's Waitlist",
        "security": [
          {
            "oauthSecurity": [
              "wait_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "waitlist-games-v1-put",
        "tags": [
          "Waitlist Games"
        ],
        "summary": "Add to Waitlist",
        "description": "Add games to user's Waitlist",
        "security": [
          {
            "oauthSecurity": [
              "wait_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "waitlist-games-v1-delete",
        "tags": [
          "Waitlist Games"
        ],
        "summary": "Delete from Waitlist",
        "description": "Delete games from user's Waitlist",
        "security": [
          {
            "oauthSecurity": [
              "wait_write"
            ]
          }
        ]
      }
    },
    "/collection/games/v1": {
      "get": {
        "operationId": "collection-games-v1-get",
        "tags": [
          "Collection Games"
        ],
        "summary": "Games in Collection",
        "description": "Get games in user's Collection",
        "security": [
          {
            "oauthSecurity": [
              "coll_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "collection-games-v1-put",
        "tags": [
          "Collection Games"
        ],
        "summary": "Add to Collection",
        "description": "Add games to user's Collection",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "collection-games-v1-delete",
        "tags": [
          "Collection Games"
        ],
        "summary": "Delete from Collection",
        "description": "Delete games from user's Collection",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      }
    },
    "/collection/copies/v1": {
      "get": {
        "operationId": "collection-copies-v1-get",
        "tags": [
          "Collection Copies"
        ],
        "summary": "List Copies",
        "description": "Get all copies user has in their Collection. Copies are returned as a simple list.\n\nIt is not necessary to have copy for each game in Collection, so you should not rely on this endpoint\nif you need to know about all games in user's Collection.\n",
        "security": [
          {
            "oauthSecurity": [
              "coll_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "collection-copies-v1-post",
        "tags": [
          "Collection Copies"
        ],
        "summary": "Add Copies",
        "description": "Add new copies. If the game is not already in a Collection, it will be added. Similarly, new tags will also be created.\n\nSame copies may exist multiple times for a single game, ITAD does not check for duplicates.\n\nThis operation is atomic, either all copies are added or none.\n",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "collection-copies-v1-patch",
        "tags": [
          "Collection Copies"
        ],
        "summary": "Update Copies",
        "description": "Update one or more copies.\n\nYou can issue partial updates on copy, only properties that are included for a copy will be updated.\n    \nThis operation is atomic, either all copies are updated or none.\n",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "collection-copies-v1-delete",
        "tags": [
          "Collection Copies"
        ],
        "summary": "Delete Copies",
        "description": "Delete Collection copies.\n\nCopies that do not exist or don't belong to user will be silently ignored.\n\nOperation is atomic. Either all copies are deleted or none.\n",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      }
    },
    "/collection/groups/v1": {
      "get": {
        "operationId": "collection-groups-v1-get",
        "tags": [
          "Collection Groups"
        ],
        "summary": "Get all Categories",
        "description": "Get all Collection categories, both the user created ones and default one.\nDefault category has id 0 and will always be listed last. User set order of categories is respected in the response.\n",
        "security": [
          {
            "oauthSecurity": [
              "coll_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "collection-groups-v1-post",
        "tags": [
          "Collection Groups"
        ],
        "summary": "Create new Category",
        "description": "Create Collection category. Categories with same name may exist.\n\nSuccessful response will return the created category.\n",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "collection-groups-v1-patch",
        "tags": [
          "Collection Groups"
        ],
        "summary": "Update Categories",
        "description": "Update one or more categories.\n\nFor each category that you are going to update, only `id` is required. Fields that you do not want to update may be\nset to `null` or omitted fully. Categories that do not exist or user does not own will be ignored.\n\nDefault category (id: `0`) may have only `public` property updated. Other properties will be ignored.\n\nThis operation is atomic, either all categories update or none. Successful response is the full category list,\ninclud[...]",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "collection-groups-v1-delete",
        "tags": [
          "Collection Groups"
        ],
        "summary": "Delete Categories",
        "description": "Delete Collection categories.\n\nDefault category or categories that do not exist or user does not own will be silently ignored.\n",
        "security": [
          {
            "oauthSecurity": [
              "coll_write"
            ]
          }
        ]
      }
    },
    "/stats/waitlist/v1": {
      "get": {
        "operationId": "stats-waitlist-v1",
        "tags": [
          "Stats",
          "Waitlist Stats"
        ],
        "summary": "Waitlist Stats",
        "description": "Get Waitlist statistics for a game\n\n> Note: stats do not take into consideration users' regions.\n> If they have set their price limit to be a historical low, stats will be computed\n> for all users as if they were in the region you specify\n",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/stats/most-waitlisted/v1": {
      "get": {
        "operationId": "stats-most-waitlisted-v1",
        "tags": [
          "Stats",
          "Waitlist Stats"
        ],
        "summary": "Most Waitlisted",
        "description": "Get list of most Waitlisted games\n",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/stats/most-collected/v1": {
      "get": {
        "operationId": "stats-most-collected-v1",
        "tags": [
          "Stats",
          "Collection Stats"
        ],
        "summary": "Most Collected",
        "description": "Get list of most Collected games\n",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/stats/most-popular/v1": {
      "get": {
        "operationId": "stats-most-popular-v1",
        "tags": [
          "Stats"
        ],
        "summary": "Most Popular",
        "description": "Get list of most popular games. Popularity for each game is computed as Waitlisted count + Collected count.\n",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/user/info/v2": {
      "get": {
        "operationId": "user-info-v2",
        "tags": [
          "User"
        ],
        "summary": "User Info",
        "description": "Get user info, currently just a username",
        "security": [
          {
            "oauthSecurity": [
              "user_info"
            ]
          }
        ]
      }
    },
    "/user/notes/v1": {
      "get": {
        "operationId": "user-notes-v1-get",
        "tags": [
          "User Notes"
        ],
        "summary": "Get notes",
        "description": "Get user's game notes\n",
        "security": [
          {
            "oauthSecurity": [
              "notes_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "user-notes-v1-put",
        "tags": [
          "User Notes"
        ],
        "summary": "Add or edit notes",
        "description": "Add or edit game notes. This operation is atomic and idempotent.\n",
        "security": [
          {
            "oauthSecurity": [
              "notes_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "user-notes-v1-delete",
        "tags": [
          "User Notes"
        ],
        "summary": "Delete notes",
        "description": "Delete game notes. This operation is atomic.\n",
        "security": [
          {
            "oauthSecurity": [
              "notes_write"
            ]
          }
        ]
      }
    },
    "/profiles/link/v1": {
      "put": {
        "operationId": "profiles-link-v1-put",
        "tags": [
          "Profiles"
        ],
        "summary": "Link profile",
        "description": "Profile is an object identifying remote account. You need linked profile to use sync endpoints.\n\nAfter successful link you will get profile token, which is used in subsequent profile operations,\nusually as an `ITAD-Profile` header. \n\nLinking is idempotent, if you lose your token, or you need it in different instance of your app,\nyou can link the same profile again.\n",
        "security": [
          {
            "oauthSecurity": [
              "profiles"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "profiles-link-v1-delete",
        "tags": [
          "Profiles"
        ],
        "summary": "Unlink profile",
        "security": [
          {
            "oauthSecurity": [
              "profiles"
            ]
          }
        ]
      }
    },
    "/profiles/sync/waitlist/v1": {
      "put": {
        "operationId": "profiles-sync-waitlist-v1-put",
        "tags": [
          "Sync"
        ],
        "summary": "Sync Waitlist",
        "description": "Sync Waitlist with IsThereAnyDeal. User can set category for your profile and default notification rules\nin their [settings](https://isthereanydeal.com/settings/profiles/), same as with natively supported profiles.\n",
        "security": [
          {
            "oauthSecurity": [
              "profiles"
            ]
          }
        ]
      }
    },
    "/profiles/sync/collection/v1": {
      "put": {
        "operationId": "profiles-sync-collection-v1-put",
        "tags": [
          "Sync"
        ],
        "summary": "Sync Collection",
        "description": "Sync Collection with IsThereAnyDeal. User can set category for your profile\nin their [settings](https://isthereanydeal.com/settings/profiles/), same as with natively supported profiles.\n\nGames are synced as redeemed copies. If there already is a redemeed copy with the same shop in user's Collection,\nnew copy will not be added.\n",
        "security": [
          {
            "oauthSecurity": [
              "profiles"
            ]
          }
        ]
      }
    },
    "/service/shops/v1": {
      "get": {
        "operationId": "service-shops-v1",
        "tags": [
          "Shops"
        ],
        "summary": "Get Shops",
        "description": "Return information about shops",
        "security": []
      }
    },
    "/internal/early-access/v1": {
      "get": {
        "operationId": "internal-earlyaccess-v1",
        "tags": [
          "Internal"
        ],
        "summary": "Early Access Games",
        "description": "Returns list of Steam appids, which are currently considered to be early in early access",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/internal/players/v1": {
      "get": {
        "operationId": "internal-players-v1",
        "tags": [
          "Internal"
        ],
        "summary": "Number of Players Statistics",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/internal/hltb/v1": {
      "get": {
        "operationId": "internal-hltb-v1",
        "tags": [
          "Internal"
        ],
        "summary": "HowLongToBeat Overview",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/internal/reviews/v1": {
      "get": {
        "operationId": "internal-reviews-v1",
        "tags": [
          "Internal"
        ],
        "summary": "Reviews Score",
        "description": "Returns Metacritic user reviews overview and OpenCritic overview for a given game",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/internal/rates/v1": {
      "get": {
        "operationId": "internal-rates-v1",
        "tags": [
          "Internal"
        ],
        "summary": "Conversion Rates",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    },
    "/internal/twitch/stream/v1": {
      "get": {
        "operationId": "internal-twitchstream-v1",
        "tags": [
          "Internal"
        ],
        "summary": "Current stream of Twitch channel",
        "security": [
          {
            "keySecurity": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "keySecurity": {
        "type": "apiKey",
        "in": "query",
        "name": "key"
      },
      "oauthSecurity": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://isthereanydeal.com/oauth/authorize/",
            "tokenUrl": "https://isthereanydeal.com/oauth/token/",
            "refreshUrl": "https://isthereanydeal.com/oauth/token/",
            "scopes": {
              "user_info": "Get basic user's info",
              "notes_read": "Read user's game notes",
              "notes_write": "Write (add, edit, delete) user's game notes",
              "profiles": "Link or unlink profiles",
              "wait_read": "Read user's Waitlist",
              "wait_write": "Write (add, edit, delete) in user's Waitlist",
              "coll_read": "Read user's Collection",
              "coll_write": "Write (add, edit, delete) in user's Collection"
            }
          }
        }
      }
    }
  },
  "x-tagGroups": [
    {
      "name": "Lookup",
      "tags": [
        "Lookup"
      ]
    },
    {
      "name": "Games",
      "tags": [
        "Game",
        "Prices",
        "History",
        "Bundles",
        "Deals List"
      ]
    },
    {
      "name": "Waitlist",
      "tags": [
        "Waitlist Games",
        "Waitlist Stats"
      ]
    },
    {
      "name": "Collection",
      "tags": [
        "Collection Games",
        "Collection Copies",
        "Collection Groups",
        "Collection Stats"
      ]
    },
    {
      "name": "Stats",
      "tags": [
        "Stats"
      ]
    },
    {
      "name": "User",
      "tags": [
        "User",
        "User Notes",
        "Profiles",
        "Sync"
      ]
    },
    {
      "name": "Shops",
      "tags": [
        "Shops"
      ]
    },
    {
      "name": "Unstable",
      "tags": [
        "Unstable"
      ]
    },
    {
      "name": "Internal",
      "tags": [
        "Internal"
      ]
    }
  ]
}