openapi: 3.1.0
info:
  title: IsThereAnyDeal API
  description: |
    IsThereAnyDeal API provides programmatic access to features found at IsThereAnyDeal.

    ## Terms of Service

    API is provided in good faith. We trust you won't misuse the API to damage IsThereAnyDeal, its users or its reputation.

    - You MAY use this API for commercial purposes **IF** the resulting app is available to public. If you want to use this API privately contact us.
    - You SHOULD provide a link to IsThereAnyDeal.com or mention IsThereAnyDeal API.
    - You MUST NOT make an impression that you are affiliated with IsThereAnyDeal, unless agreed otherwise.
      If you are interested in making an official app, please contact us.
    - You MUST NOT change provided data in any way. This means that you can't remove affiliate tags from the URLs, change prices and so on.
      You MAY use only part of data provided and enrich them from your own sources.  
    - You MUST NOT make an app that could be considered a competition to IsThereAnyDeal or IsThereAnyDeal projects.
    - You MUST NOT use this API to directly or indirectly help the competition of IsThereAnyDeal.
    
    All data are provided _as-is_. We reserve the right to deny you access to the API at any point without notice.
    If you are not sure about any of the points, please contact us.
    
    ## Access
    
    Most of the endpoints will be restricted by either API key or OAuth.
    In order to get neccessary keys, you have to [register your app](https://isthereanydeal.com/apps/my/).
    Upon registration, api keys and OAuth credentials will be generated for you.
    
    For some endpoints you might need explicit approval for use. In such cases, contact us.
    
    ### OAuth
    
    We support [authorization code](https://www.oauth.com/oauth2-servers/access-tokens/authorization-code-request/) flow with [PKCE extension](https://oauth.net/2/pkce/).
    
    > You can find PKCE step-through tutorial at [OAuth 2.0 PKCE Flow](https://www.oauth.com/playground/authorization-code-with-pkce.html)
    
    Do not set hard limits for token lengths. Server will return access token as JWT of variable length.
    To authorize your endpoint access use Authorization header.
    
    > At the moment implicit flow is also enabled, but its usage is discouraged and support may be removed in the future
    
    ## Rate Limiting
    
    Access to API is rate limited and subject to change. You should get rate-limit info in appropriate headers.
    Further limits and restrictions may be added if we detect misuse. 
    
    If you have questions about limits, contact us.
    
    # Unstable and Internal Endpoints
    
    Some endpoints are marked as unstable or internal. Unstable endpoints are publicly available,
    but the API may not be completely finalized yet - either the way the endpoint is called or the response may change
    at any time.
    
    Internal APIs are available only for our own services. They are documented here for completeness.
    
    ## Source

    You can find source files for this documentation over at [GitHub](https://github.com/IsThereAnyDeal/API).
    Feel free to help us improve it.

  version: 2.0.0
  contact:
    name: General API contact
    email: api@isthereanydeal.com
servers:
  - url: https://api.isthereanydeal.com

tags:
  - name: Game
  - name: Prices
  - name: History
  - name: Bundles
  - name: Deals List
  - name: User
  - name: Waitlist
  - name: Collection
  - name: Shops
  - name: Stats
  - name: Unstable
  - name: Internal

x-tagGroups:
  - name: Games
    tags:
      - Game
      - Prices
      - History
      - Bundles
      - Deals List
  - name: User
    tags:
      - User
      - Waitlist
      - Collection
      - Stats
  - name: Shops
    tags:
      - Shops
  - name: Unstable
    tags:
      - Unstable
  - name: Internal
    tags:
      - Internal

components:
  securitySchemes:
    keySecurity:
      type: apiKey
      in: query
      name: key

    oauthSecurity:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://isthereanydeal.com/oauth/authorize/
          tokenUrl: https://isthereanydeal.com/oauth/token/
          refreshUrl: https://isthereanydeal.com/oauth/token/
          scopes:
            user_info: Get basic user's info
            wait_read: Read user's Waitlist
            wait_write: Write (add, edit, delete) in user's Waitlist
            coll_read: Read user's Collection
            coll_write: Write (add, edit, delete) in user's Collection

  parameters:
    country:
      name: country
      in: query
      description: Two letter country code (ISO 3166-1 alpha-2)
      schema:
        type: string
        minLength: 2
        maxLength: 2
        default: "US"
    gid:
      name: id
      in: query
      required: true
      description: Game ID
      schema:
        type: string
        format: uuid
    shops:
      name: shops
      in: query
      description: List of shop IDs
      explode: false
      style: form
      schema:
        type: array
        items:
          type: integer
        example: [ 65, 35 ]

  requestBodies:
    gids:
      description: List of Game IDs
      content:
        "application/json":
          schema:
            type: array
            minItems: 1
            items:
              type: string
              format: uuid
          example: [ "01849783-6a26-7147-ab32-71804ca47e8e", "01849782-1017-7389-8de4-c97c587fd7e3" ]

    gids-200:
      description: List of Game IDs
      content:
        "application/json":
          schema:
            type: array
            minItems: 1
            maxItems: 200
            items:
              type: string
              format: uuid
          example: [ "01849783-6a26-7147-ab32-71804ca47e8e", "01849782-1017-7389-8de4-c97c587fd7e3" ]

paths:
  /service/shops/v1:
    $ref: "./routes/service/shops.v1.yaml"

  /deals/v2:
    $ref: "./routes/deals/deals.v2.yaml"

  /games/search/v1:
    $ref: "./routes/games/search.v1.yaml"
  /games/lookup/v1:
    $ref: "./routes/games/lookup.v1.yaml"
  /games/info/v2:
    $ref: "./routes/games/info.v2.yaml"
  /games/prices/v2:
    $ref: "./routes/games/prices.v2.yaml"
  /games/bundles/v2:
    $ref: "./routes/games/bundles.v2.yaml"
  /games/overview/v2:
    $ref: "./routes/games/overview.v2.yaml"
  /games/historylow/v1:
    $ref: "./routes/games/historylow.v1.yaml"
  /games/storelow/v2:
    $ref: "./routes/games/storelow.v2.yaml"
  /games/history/v2:
    $ref: "./routes/games/history.v2.yaml"

  /waitlist/games/v1:
    $ref: "./routes/waitlist/games.v1.yaml"

  /collection/games/v1:
    $ref: "./routes/collection/games.v1.yaml"

  /stats/waitlist/v1:
    $ref: "./routes/stats/waitlist.v1.yaml"
  /stats/most-waitlisted/v1:
    $ref: "./routes/stats/most-waitlisted.v1.yaml"
  /stats/most-collected/v1:
    $ref: "./routes/stats/most-collected.v1.yaml"
  /stats/most-popular/v1:
    $ref: "./routes/stats/most-popular.v1.yaml"

  /user/info/v2:
    $ref: "./routes/user/info.v2.yaml"

  /unstable/id-lookup/shop/{shopId}/v2:
    $ref: "./routes/unstable/id-lookup/shop.v2.yaml"
  /unstable/id-lookup/itad/{shopId}/v2:
    $ref: "./routes/unstable/id-lookup/itad.v2.yaml"

  /internal/early-access/v1:
    $ref: "./routes/internal/early-access.v1.yaml"
  /internal/players/v1:
    $ref: "./routes/internal/players.v1.yaml"
  /internal/hltb/v1:
    $ref: "./routes/internal/hltb.v1.yaml"
  /internal/reviews/v1:
    $ref: "./routes/internal/reviews.v1.yaml"
  /internal/rates/v1:
    $ref: "./routes/internal/rates.v1.yaml"
  /internal/twitch/stream/v1:
    $ref: "./routes/internal/twitch.stream.v1.yaml"




